### PR TITLE
add csv support to JayI

### PR DESCRIPTION
**Pull request by ghost**
The old files are incompatible but the default filename is different so it shouldn't crash

### CODE REVIEW

**Comment by raehik** [comment]
Ah, something I wanted to implement while trying to refactor too much at once -- why don't we use a `.db` extension? It's more abstract than `.txt` or `.csv` and allows us to arbitrarily switch between formats.

**Comment by ghost** [comment]
No because it would break when we upgraded the file format!

> the old files are incompatible but the default filename is different so it shouldn't crash!

**Comment by raehik** [comment]
That's the only thing I was thinking about. My main reasoning was that users should not be told the file format unless they need it, but I never made up my mind about whether users should be able to view the database. With CSV it would be useful, because then people could know "oh, I could import this to [Excel]' or w/e.

**Comment by spudowiar** [comment]
btw, i am now @spudowiar

**Comment by spudowiar** [comment]
but yes, freedom for the people FTW!

**Pull request merged**
